FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS build
WORKDIR /LMSApi2

# copy csproj and restore as distinct layers
COPY *.sln .
COPY LMSApi2/*.csproj ./LMSApi2/
RUN dotnet restore

# copy everything else and build app
COPY LMSApi2/. ./LMSApi2/
WORKDIR /LMSApi2/LMSApi2
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /LMSApi2
COPY --from=build /LMSApi2/LMSApi2/out .
EXPOSE 80
CMD ["dotnet", "LMSApi2.dll"]