FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src
COPY ["LMSApi2.csproj", "."]
RUN dotnet restore "./LMSApi2.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "LMSApi2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LMSApi2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
CMD ASPNETCORE_URLS=http://*:$PORT dotnet LMSApi2.dll